### ISSUE TITLE
Queries

### ISSUE THREAD

**Issue by akiranmutnuru** [TWCable/grabbit#111]
1)	How can we know, on copying which node, we are getting the error/Failure?
2)	How many paths (filters) at max we can keep in configuration file? 
3)	Will there be any problem if we put more number of filters in configuration files?
4)	Where are we keeping the configuration regarding no of nodes to be copied/saved at a time. Please share.
5)	How to tune specifying multiple focused paths, parallel or serial execution, JCR Session batch size (the number of nodes to cache before flushing to disk), ? I request you to please share 
6)     also please share how to exclude some paths something like below
/content/(.*)?localization(/.*)?

Thanks a million Sarar :-)

**Comment by jbornemann** [comment]
1.) Currently, the batch-server.log, and batch-client.log are your best bets. Depending on what layer the issue occurs, and especially if the error log is vague in the matter, most of the time it's an issue with some aggregation of nodes (memory limits, stale sessions, etc), rather than one particular node. That said, we definitely have some work to do on making the logs more clear on what went wrong : https://github.com/TWCable/grabbit/issues/66

2.) We don't enforce any limits. Currently Grabbit will process 10 jobs at a time, then as jobs free up,  new jobs will be assigned to those threads. 

3.) There shouldn't be. Are you seeing issues?

4.) Nodes are copied in a continuous stream, so there is no configuration regarding that; however, nodes are saved/read in batches. I don't believe we have this configuration tweak-able at the moment. We manage it in an internal configuration file (grabbit/src/main/resources/META-INF.spring/client-batch-job.xml, which I believe is currently set to 100. 

5.) I think I may know what you are asking on this one, but do you mind elaborating so I can be sure?

6.) Mind providing another example? I'm a bit confused about the one above. We don't currently have regex-style paths supported. You can, however, exclude subpaths through the "excludePaths" property. e.g:

```
/content/cars/ford
/content/cars/ford/jcr:content
/content/cars/honda
/content/cars/honda/jcr:content
```
```
path: '/content/cars'
excludePaths: 
  - 'ford'
  - 'chevy'
```

**Comment by jdigger** [comment]
@akiranmutnuru - Did Jeff's response answer your question?

**Comment by jdigger** [comment]
Assuming the questions have been answered.
