### ISSUE TITLE
Is there any way to clean the old jobs in /grabbit/job/all.json ??

### ISSUE THREAD

**Issue by akiranmutnuru** [TWCable/grabbit#137]
I am using Grabbit 3.0.5 on AEM 5.6
Is there any way to clean the old jobs in /grabbit/job/all.json ??
i am getting all the jobs which run from starting.
i just wanted to clean all the jobs 

please help me. Thanks a million:)

**Comment by jdigger** [comment]
For v5+ check out https://github.com/TWCable/grabbit/blob/master/docs/Cleaning.adoc

For v3.x you can delete the nodes under `/var/grabbit`

**Comment by sagarsane** [comment]
Just to add to that..
For v3.x, if you directly delete nodes under "/var/grabbit", make sure you
stop and start the Grabbit bundle. (or a cq restart also works of course
but you can just stop / start the bundle as well)

**Comment by akiranmutnuru** [comment]
Thanks a million to both of you:)

One more question:
how to get the all the job ids of current execution?
I mean, if i start execution grabbit.sh, let's say 30 jobs executed.
i want all the job ids automatically of current execution.
is there any way i get them. 
i aware that, i can get it from all.json file, but apart from that, Can i get it from any other way ?

**Comment by jbornemann** [comment]
Hey @akiranmutnuru , for 3.0.5 there isn't a great way to do this. For later versions, we added the concept of transactions which is essentially exactly what you described. For later versions, you can monitor using a transactionID provided when you kick off a set of jobs, and the/grabbit/transaction/<transactionID> endpoint. 

Of course, we always accept PRs for backporting features to earlier AEM support versions. :-)

**Comment by sagarsane** [comment]
Just to add to what @jbornemann said, v5.0.0 onwards is where we added the transactions support so that you can `track current set of jobs being executed as one transaction`.

Here's the release that introduced it : https://github.com/TWCable/grabbit/releases/tag/v5.0.0 (in case you need to see what the changes were and how they were done)

Here's some documentation around the transaction support for v5.0.0 onwards : https://github.com/TWCable/grabbit/blob/master/docs/Monitoring.adoc

**Comment by akiranmutnuru** [comment]
Thanks a million to both of you again.
