### ISSUE TITLE
Version Compatibility

### ISSUE THREAD

**Issue by moal321** [TWCable/grabbit#152]
Hello!

Is it possible to transfer content from CQ 5.6.1 to AEM 6.1?
If yes, which version(s) of Grabbit do I need to use?

**Comment by sagarsane** [comment]
Hi @moal321,

Yes it is possible to use Grabbit for this. However, you will have to use older versions. 

Here's the doc for version support : https://github.com/TWCable/grabbit/blob/master/docs/AEMSupport.adoc#below-details-aem-version-support-for-the-various-releases-of-grabbit

I believe the last `v3.x` for CQ 5.6.1 and the last `v4.x` for AEM 6.1 should work (but ofcourse, you will not have all the "latest" features that are in the newer versions).

`v5.x` and `v7.x` won't work because they diverged from `v3.x` which was the last one for CQ 5.6.1 in core functionality.

More info on releases and the functionalities : https://github.com/TWCable/grabbit/releases

**Comment by moal321** [comment]
Thank you for the answer!
I will provide feedback as soon as I have time to try this out.

**Comment by jbornemann** [comment]
@moal321 just to add onto what Sagar has said - For most common vanilla content (cq:Page, nt:unstructured, etc), Grabbit can be used to transfer content between AEM versions; However, note that there is some content whose node definitions have diverged, so you may run into issues for some items - I'm having trouble remembering specific examples off the top of my head though. They are all within the CQ namespace of course..

**Comment by jbornemann** [comment]
Hey @moal321, any luck?

**Comment by jbornemann** [comment]
Hey @moal321, I hope we helped in some way. In the spirit of keeping our issue list relatively organized, I'm going to close this out. Please reopen this if we can help you with this further!
