### ISSUE TITLE
Java8, AEM6.1 SP2 - Error with sun.misc Import-Package

### ISSUE THREAD

**Issue by AnselmHa** [TWCable/grabbit#153]
Grabbit OSGi Bundle cannot be installed at AEM6.1 SP2 Java8
see <your-AEM-instance>/system/console/bundles/com.twcable.grabbit
sun.misc -- Cannot be resolved and overwritten by Boot Delegation

Message in Log:
[FelixDispatchQueue] com.twcable.grabbit ...  Unresolved constraint in bundle com.twcable.grabbit ... missing requirement [1251.0] osgi.wiring.package; (osgi.wiring.package=sun.misc)

Problem comes with change: https://github.com/TWCable/grabbit/pull/53/files#r36194643
+    instruction 'Import-Package', "sun.misc"

Further information:
https://www.infoq.com/news/2013/09/remove-sun.misc.sort-java-8

Yes there would be a workaround (org.osgi.framework.system.packages.extra=sun.misc), but we don't think that is appropriated:
- https://github.com/ReactiveX/RxJava/issues/3516
- https://github.com/diffplug/osgiX

**Comment by viveksachdeva** [comment]
@AnselmHa :
Did you install https://bintray.com/artifact/download/twcable/aem/dependencies/Sun-Misc-Fragment-Bundle-1.0.0.zip as mentioned in https://github.com/TWCable/grabbit/blob/master/docs/AEMSupport.adoc

**Comment by AnselmHa** [comment]
Good hint to another workaround, but still the same problem with org.osgi.framework.system.packages.extra=sun.misc, we don't want to put extra packages in or enhance system bundle for a tool, that is no good practice and prevents using it in our point of view.
I would prefer an solution on grabbit bundle level, if possible, as mentioned in official Oracle docu "The sun.* packages are not part of the supported, public interface." see http://www.oracle.com/technetwork/java/faq-sun-packages-142232.html

**Comment by sagarsane** [comment]
Hi @AnselmHa, the sun-misc-fragment-bundle content package mentioned above is a required dependency for Grabbit as mentioned in the documentation linked by @viveksachdeva above. All it does is it exports just the "sun.misc" package from OSGi System bundle.

It is required by Groovy (Groovy's json implementation has a runtime dependency on sun.misc) and thus currently required by Grabbit since its built on Groovy.

As mentioned in the ReactiveX link above, you can also use bootdelegation to achieve the same but installing the sun-misc-fragment-bundle package is more straightforward.

As mentioned in #125, once Grabbit is migrated from Groovy to Java8, this dependency will no longer be required. However, as of now, it is required dependency.

Hope this helps!

**Comment by jbornemann** [comment]
Hey @AnselmHa , did @sagarsane 's comment help resolve your issue?

**Comment by AnselmHa** [comment]
Thank you for your help, the fragment bundle solved it. Unfortunately I had to remove Grabbit again because of bringing incompatible  Servicemix versions on the system. 
As a side note. We are using the groovy-script-console without any problem. Maybe there is a possibility to do your stuff more the way they did (e.g. using no extra bundle).

**Comment by sagarsane** [comment]
Yeah @AnselmHa, groovy-console doesn't have this issue because it doesn't use Groovy's JSON implementation at runtime (that I know of).

Grabbit has a minor use of JSON for some user interactions.
