### ISSUE TITLE
Delta content syncs

### ISSUE THREAD

**Issue by jdigger** [TWCable/grabbit#39]
The feature is "implemented" but it never got properly tested.

https://github.com/TWCable/grabbit/search?utf8=%E2%9C%93&q=deltaContent

It's based on last successful jobexecution "endTime" for a path on the client.

https://github.com/TWCable/grabbit/blob/844b0d13abec0a693990f323cf3e6a2693e366a1/grabbit/src/main/groovy/com/twcable/grabbit/servlets/GrabbitServlet.groovy#L65

https://github.com/TWCable/grabbit/blob/844b0d13abec0a693990f323cf3e6a2693e366a1/grabbit/src/main/groovy/com/twcable/grabbit/client/batch/ClientBatchJob.groovy#L200-L215 

Needs cleanup, testing and documentation.

**Comment by egenz** [comment]
To set deltaContent, you may need to add the line:
`"deltaContent" : true,`
if it is not already present in your grabbit-publish-dev.json file.

The deltaContent setting determines what is new content based on the 'afterDateString' (seen in the second link above) and synchs only those nodes to the client.

Test Cases (done by synching with Grabbit from AEM 6.1 author instance to publish instance):
* Adding or copying a component to a page:
 * Works with deltaContent as expected, updates with Grabbit.

* Modifying a component with no created date (only "LastModified" date) [e.g. an Image in a Slide Component]: 
 * Changing LastModified Date trips deltaContent, updates w/ Grabbit
 * (as expected) just changing the image on the node, without updating LastModified, doesn't work.

* Modifying a component with a 'created' and LastModified date [e.g. Button component]
 * Changing LastModified date *doesn't* work, running grabbit does not update the page
 * Changing 'created' date does work, and the instance updates with grabbit. (even if lastModified stays the same)
 * May be due to logic within grabbit which returns 'date' as either 'created' OR 'lastModified', so these are not both included in the information grabbit knows about a particular node. When only the 'created' date is understood as the date, the 'afterDateString' won't realize the node has been updated.

* Deleting a component:
 * Doesn't work, as expected.

* Testing a larger path (170,000 nodes):
 * Still correctly only updates a single node.

* Multiple Changes (ie, changing created date on a button and modified date on rich text):
 * Only successfully syncs components which have properly updated 'lastModified' or 'created' dates as experienced above
